C
C   System variables accessed by user
C
        Logical ReEval_Derivs,
     &          Stop_Simulation
        Equivalence (Real_Array( 1), Time)
        Equivalence (Real_Array( 2), Time0)
        Equivalence (Real_Array( 3), TStop)
        Equivalence (Real_Array( 4), Dt)
        Equivalence (Real_Array( 5), DtMax)
        Equivalence (Real_Array( 6), DtMin)
        Equivalence (Real_Array( 7), DtPrint)
        Equivalence (Real_Array( 8), ReEval_Derivs)
        Equivalence (Real_Array( 9), Stop_Simulation)
C
